# Discord Bot Core
# This file must be placed in the same folder as where you run `npm start` or `node .` (for ./dist)

token: "NjA2MDA1NDkxOTY0OTY4OTYz.XUEwmA.n-hWENkNIKm36S8aKYMNaero2N0"

# =====================================
# =           STYLE OPTIONS           =
# =====================================
embeds:
  primary:
    color: "#548CFF"
  error:
    color: "#F14A16"